-- Initial menu from the existing website. Verify portion names before launch.
insert into public.menu_items (id,name,category,description,price,sort_order) values
('burgers-0-0','Xtreme Boss Burger (beef)','Burgers','Double smash beef, crispy beef bacon, fried egg, signature glaze & melted cheese.',381,0),
('burgers-1-0','Drip Beast Burger (beef)','Burgers','Juicy smashed beef loaded with caramelized onions, liquid cheese drip & relish.',376,1),
('burgers-2-0','Dallas Smashed Burger (beef)','Burgers','Smoky Texas BBQ glaze, crispy onion rings and double American cheddar.',264,2),
('burgers-3-0','BBQ Smashed Burger (beef)','Burgers','Double grilled smash beef with sweet hickory smoke BBQ sauce.',289,3),
('burgers-4-0','Manhattan Melt Burger (beef)','Burgers','Classic NYC smash burger style, grilled onions, pickles and diner mustard sauce.',199,4),
('burgers-5-0','Gooey Burger (beef)','Burgers','Ultra-melty cheesy smash beef burger with house secret sauce and soft bun.',189,5),
('burgers-6-0','Beef Bacon Burger (beef)','Burgers','Smashed beef patty layered with premium crispy smoked beef bacon and melted cheese.',342,6),
('burgers-7-0','Xtreme Boss Burger (chicken)','Burgers','Crispy fried chicken fillet, beef bacon, melted cheese, egg and signature glaze.',361,7),
('burgers-8-0','Hexxa Burger (chicken)','Burgers','Crispy fried chicken stacked with signature sauce, fresh slaw and cheddar.',359,8),
('burgers-9-0','Ranch Burger (chicken)','Burgers','Buttermilk fried chicken, creamy herb ranch, dill pickles and crisp iceberg.',314,9),
('burgers-10-0','Grillzilla Burger (chicken)','Burgers','Flame-grilled juicy chicken fillet seasoned to perfection with melted cheese.',220,10),
('burgers-11-0','DXB Spicy (chicken)','Burgers','Crispy chicken infused with fiery spicy cayenne glaze and pickled jalapenos.',198,11),
('burgers-12-0','DXB Classic (chicken)','Burgers','The original golden bun, fresh leaf lettuce, juicy chicken patty and house spread.',188,12),
('starters-0-0','Fries — option 1','Starters','Crispy skin-on golden potato fries seasoned with sea salt.',79,13),
('starters-0-1','Fries — option 2','Starters','Crispy skin-on golden potato fries seasoned with sea salt.',159,14),
('starters-0-2','Fries — option 3','Starters','Crispy skin-on golden potato fries seasoned with sea salt.',189,15),
('starters-1-0','Piri Piri Fries — option 1','Starters','Tossed in signature tangy African birds eye piri piri dust.',99,16),
('starters-1-1','Piri Piri Fries — option 2','Starters','Tossed in signature tangy African birds eye piri piri dust.',179,17),
('starters-1-2','Piri Piri Fries — option 3','Starters','Tossed in signature tangy African birds eye piri piri dust.',209,18),
('starters-2-0','Loaded Fries','Starters','Topped with melted cheese, savory beef mince, jalapenos and house sauce.',210,19),
('starters-3-0','Chicken Fingers','Starters','Crispy golden tender chicken fingers served with dipping sauce.',189,20),
('starters-4-0','Chicken Nuggets','Starters','Golden bite-sized chicken nuggets crispy on the outside, tender inside.',188,21),
('starters-5-0','Mozzarella Sticks','Starters','Gooey melted mozzarella coated in seasoned herb breadcrumbs with marinara.',210,22),
('starters-6-0','Japanese Prawn Island','Starters','Crisp tempura-battered succulent prawns served with signature dip.',248,23),
('starters-7-0','Tokyo Street Chicken Wings','Starters','Crispy chicken wings glazed street-style with toasted sesame and scallions.',189,24),
('starters-8-0','Potato Wedges','Starters','Thick rustic seasoned potato wedges served golden and crispy.',178,25),
('starters-9-0','Piri Piri Potato Wedges','Starters','Crispy potato wedges tossed in zesty fiery piri piri seasoning.',198,26),
('rice-pasta-0-0','Heavenly Vision Bowl','Rice & Pasta','Aromatic seasoned butter rice served with grilled chicken, greens and garlic cream.',299,27),
('rice-pasta-1-0','Third Eye Awakening Bowl','Rice & Pasta','Bold spicy wok-tossed rice bowl with charred peppers and signature spices.',319,28),
('rice-pasta-2-0','Budha Rice Bowl','Rice & Pasta','Fresh greens, toasted sesame, pickled slaw and wholesome warm seasoned rice.',289,29),
('rice-pasta-3-0','Signature House Pasta','Rice & Pasta','Silky rich signature pasta tossed with fresh herbs, garlic parmesan cream and penne.',276,30),
('rice-pasta-4-0','Arrabbiata Pasta','Rice & Pasta','Rich roasted tomato sugo, chili flakes, fresh basil, garlic and tender penne.',287,31),
('shakes-fizzy-0-0','Caremal Shake','Shakes & Fizzy','Rich creamy milkshake infused with golden buttery caramel swirl.',129,32),
('shakes-fizzy-1-0','Chocolate Shake','Shakes & Fizzy','Decadent Dutch cocoa blended with velvety ice cream and dark chocolate drizzle.',121,33),
('shakes-fizzy-2-0','Taro Shake','Shakes & Fizzy','Creamy exotic purple taro root shake with a velvety, subtly sweet finish.',139,34),
('shakes-fizzy-3-0','Mojito','Shakes & Fizzy','Refreshing muddled fresh mint leaves, zesty lime and chilled sparkling soda.',99,35),
('shakes-fizzy-4-0','Cola','Shakes & Fizzy','Classic ice-cold carbonated cola poured over ice.',49,36),
('shakes-fizzy-5-0','Sprite','Shakes & Fizzy','Crisp, refreshing lemon-lime fizzy soda served ice cold.',49,37),
('hot-cold-0-0','Hazelnut Coffee','Hot & Cold','Freshly brewed hot coffee infused with toasted aromatic hazelnut notes.',49,38),
('hot-cold-1-0','Coffee','Hot & Cold','Classic hot brewed rich coffee, balanced and invigorating.',30,39),
('hot-cold-2-0','Iced Latte','Hot & Cold','Freshly pulled espresso poured over cold milk and crystalline ice.',99,40),
('hot-cold-3-0','Iced Matcha','Hot & Cold','Authentic stone-ground green tea matcha whisked smooth over chilled milk.',139,41),
('hot-cold-4-0','Iced Frapichino','Hot & Cold','Blended iced espresso frappe topped with chilled creamy froth.',149,42),
('french-toast-0-0','Blueberry Heaven','French Toast','Golden thick-cut brioche french toast drenched in wild blueberry compote.',278,43),
('french-toast-1-0','Caremal Fountain','French Toast','Buttery toasted brioche drizzled with overflowing warm amber caramel.',249,44),
('french-toast-2-0','Chocolate Overloaded','French Toast','Crispy golden toast drenched in warm melted Belgian chocolate and chocolate pearls.',239,45),
('egyptian-desserts-0-0','Dubai Chocolate','Egyptian Desserts','Roasted golden kataifi kunafa pastry layered with rich pistachio cream and milk chocolate.',179,46),
('egyptian-desserts-1-0','Hazelnut','Egyptian Desserts','Velvety dessert cup layered with smooth hazelnut chocolate cream and crispy wafer.',179,47),
('egyptian-desserts-2-0','Milk Choco','Egyptian Desserts','Creamy Belgian milk chocolate dessert with a silky smooth, decadent finish.',179,48),
('egyptian-desserts-3-0','Half & Half','Egyptian Desserts','The best of both worlds — layered milk chocolate and rich white cream.',179,49),
('egyptian-desserts-4-0','Kinder Bueno','Egyptian Desserts','Layered white chocolate cream, roasted hazelnut wafer crunch and cocoa drizzle.',179,50)
on conflict (id) do nothing;
